// Auto-generated from shopler-catalogue-40-skus.xlsx — do not edit by hand.
// Mirror of products.json, loaded as a <script> so the app runs from file://
window.PRODUCTS = [
  {
    "sku": "AO-W-001",
    "image": "AO-W-001.jpg",
    "image_lifestyle": "AO-W-001-2.jpg",
    "name_en": "Ribbed knit jumper",
    "name_nl": "Geribde gebreide trui",
    "brand": "Atelier Ode",
    "category": "Women",
    "subcategory": "Knitwear",
    "gender": "f",
    "price_eur": 59.95,
    "sale_price_eur": null,
    "stock": 12,
    "color": "Cream",
    "material": "Cotton blend",
    "season": "AW",
    "popularity": 78,
    "pairs_with": [
      "VO-A-003",
      "NO-W-002"
    ]
  },
  {
    "sku": "AO-W-002",
    "image": "AO-W-002.jpg",
    "image_lifestyle": "AO-W-002-2.jpg",
    "name_en": "Wide-leg trouser",
    "name_nl": "Wijde pantalon",
    "brand": "Atelier Ode",
    "category": "Women",
    "subcategory": "Trousers",
    "gender": "f",
    "price_eur": 69.95,
    "sale_price_eur": 49.95,
    "stock": 7,
    "color": "Black",
    "material": "Viscose",
    "season": "AW",
    "popularity": 84,
    "pairs_with": [
      "AO-W-001",
      "VO-A-001"
    ]
  },
  {
    "sku": "AO-M-003",
    "image": "AO-M-003.jpg",
    "image_lifestyle": "AO-M-003-2.jpg",
    "name_en": "Merino crew jumper",
    "name_nl": "Merino trui",
    "brand": "Atelier Ode",
    "category": "Men",
    "subcategory": "Knitwear",
    "gender": "m",
    "price_eur": 64.95,
    "sale_price_eur": null,
    "stock": 2,
    "color": "Navy",
    "material": "Merino wool",
    "season": "AW",
    "popularity": 71,
    "pairs_with": [
      "KE-M-002",
      "VO-A-002"
    ]
  },
  {
    "sku": "AO-M-004",
    "image": "AO-M-004.jpg",
    "image_lifestyle": "AO-M-004-2.jpg",
    "name_en": "Pleated chino",
    "name_nl": "Geplooide chino",
    "brand": "Atelier Ode",
    "category": "Men",
    "subcategory": "Trousers",
    "gender": "m",
    "price_eur": 59.95,
    "sale_price_eur": null,
    "stock": 10,
    "color": "Stone",
    "material": "Cotton",
    "season": "AW",
    "popularity": 66,
    "pairs_with": [
      "AO-M-003",
      "LU-M-002"
    ]
  },
  {
    "sku": "AO-W-005",
    "image": "AO-W-005.jpg",
    "image_lifestyle": "AO-W-005-2.jpg",
    "name_en": "Wool-blend coat",
    "name_nl": "Wollen mantel",
    "brand": "Atelier Ode",
    "category": "Women",
    "subcategory": "Outerwear",
    "gender": "f",
    "price_eur": 119.95,
    "sale_price_eur": 89.95,
    "stock": 4,
    "color": "Camel",
    "material": "Wool blend",
    "season": "AW",
    "popularity": 92,
    "pairs_with": [
      "AO-W-002",
      "VO-A-001"
    ]
  },
  {
    "sku": "AO-U-006",
    "image": "AO-U-006.jpg",
    "image_lifestyle": "AO-U-006-2.jpg",
    "name_en": "Cashmere-touch scarf",
    "name_nl": "Sjaal cashmere-touch",
    "brand": "Atelier Ode",
    "category": "Accessories",
    "subcategory": "Scarves",
    "gender": "u",
    "price_eur": 34.95,
    "sale_price_eur": null,
    "stock": 18,
    "color": "Grey",
    "material": "Acrylic blend",
    "season": "AW",
    "popularity": 58,
    "pairs_with": [
      "AO-W-005",
      "AO-M-003"
    ]
  },
  {
    "sku": "AO-W-007",
    "image": "AO-W-007.jpg",
    "image_lifestyle": "AO-W-007-2.jpg",
    "name_en": "Satin midi skirt",
    "name_nl": "Satijnen midirok",
    "brand": "Atelier Ode",
    "category": "Women",
    "subcategory": "Skirts",
    "gender": "f",
    "price_eur": 49.95,
    "sale_price_eur": null,
    "stock": 3,
    "color": "Olive",
    "material": "Satin",
    "season": "AW",
    "popularity": 69,
    "pairs_with": [
      "AO-W-001",
      "VO-A-003"
    ]
  },
  {
    "sku": "AO-M-008",
    "image": "AO-M-008.jpg",
    "image_lifestyle": "AO-M-008-2.jpg",
    "name_en": "Overshirt jacket",
    "name_nl": "Overshirt jas",
    "brand": "Atelier Ode",
    "category": "Men",
    "subcategory": "Outerwear",
    "gender": "m",
    "price_eur": 74.95,
    "sale_price_eur": 54.95,
    "stock": 6,
    "color": "Charcoal",
    "material": "Cotton twill",
    "season": "AW",
    "popularity": 75,
    "pairs_with": [
      "AO-M-004",
      "KE-M-001"
    ]
  },
  {
    "sku": "NO-W-001",
    "image": "NO-W-001.jpg",
    "image_lifestyle": "NO-W-001-2.jpg",
    "name_en": "Cropped t-shirt",
    "name_nl": "Cropped t-shirt",
    "brand": "Noreen",
    "category": "Women",
    "subcategory": "Tops",
    "gender": "f",
    "price_eur": 15.95,
    "sale_price_eur": null,
    "stock": 40,
    "color": "White",
    "material": "Cotton",
    "season": "SS",
    "popularity": 62,
    "pairs_with": [
      "NO-W-003",
      "AO-W-002"
    ]
  },
  {
    "sku": "NO-W-002",
    "image": "NO-W-002.jpg",
    "image_lifestyle": "NO-W-002-2.jpg",
    "name_en": "Floral wrap dress",
    "name_nl": "Bloemen wikkeljurk",
    "brand": "Noreen",
    "category": "Women",
    "subcategory": "Dresses",
    "gender": "f",
    "price_eur": 44.95,
    "sale_price_eur": 29.95,
    "stock": 9,
    "color": "Print",
    "material": "Viscose",
    "season": "SS",
    "popularity": 88,
    "pairs_with": [
      "VO-A-001",
      "NO-W-005"
    ]
  },
  {
    "sku": "NO-W-003",
    "image": "NO-W-003.jpg",
    "image_lifestyle": "NO-W-003-2.jpg",
    "name_en": "High-waist jeans",
    "name_nl": "High-waist jeans",
    "brand": "Noreen",
    "category": "Women",
    "subcategory": "Jeans",
    "gender": "f",
    "price_eur": 39.95,
    "sale_price_eur": null,
    "stock": 15,
    "color": "Mid blue",
    "material": "Denim",
    "season": "All",
    "popularity": 80,
    "pairs_with": [
      "NO-W-001",
      "KE-W-006"
    ]
  },
  {
    "sku": "NO-W-004",
    "image": "NO-W-004.jpg",
    "image_lifestyle": "NO-W-004-2.jpg",
    "name_en": "Oversized hoodie",
    "name_nl": "Oversized hoodie",
    "brand": "Noreen",
    "category": "Women",
    "subcategory": "Tops",
    "gender": "f",
    "price_eur": 34.95,
    "sale_price_eur": null,
    "stock": 3,
    "color": "Lilac",
    "material": "Cotton blend",
    "season": "All",
    "popularity": 73,
    "pairs_with": [
      "NO-W-003",
      "LU-W-001"
    ]
  },
  {
    "sku": "NO-W-005",
    "image": "NO-W-005.jpg",
    "image_lifestyle": "NO-W-005-2.jpg",
    "name_en": "Strappy sandals",
    "name_nl": "Sandalen met bandjes",
    "brand": "Noreen",
    "category": "Women",
    "subcategory": "Shoes",
    "gender": "f",
    "price_eur": 29.95,
    "sale_price_eur": 19.95,
    "stock": 11,
    "color": "Tan",
    "material": "Synthetic",
    "season": "SS",
    "popularity": 64,
    "pairs_with": [
      "NO-W-002",
      "VO-A-001"
    ]
  },
  {
    "sku": "NO-W-006",
    "image": "NO-W-006.jpg",
    "image_lifestyle": "NO-W-006-2.jpg",
    "name_en": "Linen blouse",
    "name_nl": "Linnen blouse",
    "brand": "Noreen",
    "category": "Women",
    "subcategory": "Tops",
    "gender": "f",
    "price_eur": 27.95,
    "sale_price_eur": null,
    "stock": 20,
    "color": "Sky",
    "material": "Linen",
    "season": "SS",
    "popularity": 59,
    "pairs_with": [
      "NO-W-003",
      "AO-W-002"
    ]
  },
  {
    "sku": "NO-W-007",
    "image": "NO-W-007.jpg",
    "image_lifestyle": "NO-W-007-2.jpg",
    "name_en": "Pleated mini skirt",
    "name_nl": "Geplooide minirok",
    "brand": "Noreen",
    "category": "Women",
    "subcategory": "Skirts",
    "gender": "f",
    "price_eur": 24.95,
    "sale_price_eur": null,
    "stock": 4,
    "color": "Black",
    "material": "Polyester",
    "season": "All",
    "popularity": 55,
    "pairs_with": [
      "NO-W-001",
      "NO-W-005"
    ]
  },
  {
    "sku": "NO-W-008",
    "image": "NO-W-008.jpg",
    "image_lifestyle": "NO-W-008-2.jpg",
    "name_en": "Knit cardigan",
    "name_nl": "Gebreid vest",
    "brand": "Noreen",
    "category": "Women",
    "subcategory": "Knitwear",
    "gender": "f",
    "price_eur": 36.95,
    "sale_price_eur": null,
    "stock": 14,
    "color": "Oatmeal",
    "material": "Cotton blend",
    "season": "AW",
    "popularity": 61,
    "pairs_with": [
      "NO-W-006",
      "AO-W-007"
    ]
  },
  {
    "sku": "KE-M-001",
    "image": "KE-M-001.jpg",
    "image_lifestyle": "KE-M-001-2.jpg",
    "name_en": "Slim-fit jeans",
    "name_nl": "Slim-fit jeans",
    "brand": "Kessler",
    "category": "Men",
    "subcategory": "Jeans",
    "gender": "m",
    "price_eur": 44.95,
    "sale_price_eur": null,
    "stock": 22,
    "color": "Indigo",
    "material": "Denim",
    "season": "All",
    "popularity": 85,
    "pairs_with": [
      "KE-M-003",
      "AO-M-003"
    ]
  },
  {
    "sku": "KE-M-002",
    "image": "KE-M-002.jpg",
    "image_lifestyle": "KE-M-002-2.jpg",
    "name_en": "Graphic t-shirt",
    "name_nl": "T-shirt met print",
    "brand": "Kessler",
    "category": "Men",
    "subcategory": "Tops",
    "gender": "m",
    "price_eur": 17.95,
    "sale_price_eur": null,
    "stock": 35,
    "color": "Black",
    "material": "Cotton",
    "season": "SS",
    "popularity": 70,
    "pairs_with": [
      "KE-M-001",
      "LU-M-002"
    ]
  },
  {
    "sku": "KE-M-003",
    "image": "KE-M-003.jpg",
    "image_lifestyle": "KE-M-003-2.jpg",
    "name_en": "Hooded sweatshirt",
    "name_nl": "Hoodie",
    "brand": "Kessler",
    "category": "Men",
    "subcategory": "Tops",
    "gender": "m",
    "price_eur": 39.95,
    "sale_price_eur": 29.95,
    "stock": 8,
    "color": "Grey marl",
    "material": "Cotton blend",
    "season": "All",
    "popularity": 82,
    "pairs_with": [
      "KE-M-001",
      "VO-A-004"
    ]
  },
  {
    "sku": "KE-M-004",
    "image": "KE-M-004.jpg",
    "image_lifestyle": "KE-M-004-2.jpg",
    "name_en": "Field jacket",
    "name_nl": "Field jacket",
    "brand": "Kessler",
    "category": "Men",
    "subcategory": "Outerwear",
    "gender": "m",
    "price_eur": 89.95,
    "sale_price_eur": null,
    "stock": 5,
    "color": "Khaki",
    "material": "Cotton",
    "season": "AW",
    "popularity": 79,
    "pairs_with": [
      "KE-M-001",
      "VO-A-002"
    ]
  },
  {
    "sku": "KE-M-005",
    "image": "KE-M-005.jpg",
    "image_lifestyle": "KE-M-005-2.jpg",
    "name_en": "Cargo trouser",
    "name_nl": "Cargobroek",
    "brand": "Kessler",
    "category": "Men",
    "subcategory": "Trousers",
    "gender": "m",
    "price_eur": 49.95,
    "sale_price_eur": null,
    "stock": 2,
    "color": "Sand",
    "material": "Cotton",
    "season": "All",
    "popularity": 68,
    "pairs_with": [
      "KE-M-002",
      "VO-A-004"
    ]
  },
  {
    "sku": "KE-W-006",
    "image": "KE-W-006.jpg",
    "image_lifestyle": "KE-W-006-2.jpg",
    "name_en": "Boyfriend jeans",
    "name_nl": "Boyfriend jeans",
    "brand": "Kessler",
    "category": "Women",
    "subcategory": "Jeans",
    "gender": "f",
    "price_eur": 42.95,
    "sale_price_eur": 32.95,
    "stock": 13,
    "color": "Light blue",
    "material": "Denim",
    "season": "All",
    "popularity": 72,
    "pairs_with": [
      "NO-W-001",
      "NO-W-004"
    ]
  },
  {
    "sku": "KE-M-007",
    "image": "KE-M-007.jpg",
    "image_lifestyle": "KE-M-007-2.jpg",
    "name_en": "Flannel overshirt",
    "name_nl": "Flanellen overshirt",
    "brand": "Kessler",
    "category": "Men",
    "subcategory": "Tops",
    "gender": "m",
    "price_eur": 34.95,
    "sale_price_eur": null,
    "stock": 0,
    "color": "Red check",
    "material": "Cotton",
    "season": "AW",
    "popularity": 57,
    "pairs_with": [
      "KE-M-001",
      "KE-M-002"
    ]
  },
  {
    "sku": "KE-M-008",
    "image": "KE-M-008.jpg",
    "image_lifestyle": "KE-M-008-2.jpg",
    "name_en": "Polo shirt",
    "name_nl": "Poloshirt",
    "brand": "Kessler",
    "category": "Men",
    "subcategory": "Tops",
    "gender": "m",
    "price_eur": 22.95,
    "sale_price_eur": null,
    "stock": 26,
    "color": "White",
    "material": "Piqué cotton",
    "season": "SS",
    "popularity": 60,
    "pairs_with": [
      "KE-M-001",
      "AO-M-004"
    ]
  },
  {
    "sku": "LU-W-001",
    "image": "LU-W-001.jpg",
    "image_lifestyle": "LU-W-001-2.jpg",
    "name_en": "Organic cotton tee",
    "name_nl": "Biologisch katoenen tee",
    "brand": "Lün",
    "category": "Women",
    "subcategory": "Tops",
    "gender": "f",
    "price_eur": 12.95,
    "sale_price_eur": null,
    "stock": 50,
    "color": "Ecru",
    "material": "Organic cotton",
    "season": "All",
    "popularity": 54,
    "pairs_with": [
      "NO-W-003",
      "LU-W-003"
    ]
  },
  {
    "sku": "LU-M-002",
    "image": "LU-M-002.jpg",
    "image_lifestyle": "LU-M-002-2.jpg",
    "name_en": "Heavyweight tee",
    "name_nl": "Heavyweight tee",
    "brand": "Lün",
    "category": "Men",
    "subcategory": "Tops",
    "gender": "m",
    "price_eur": 14.95,
    "sale_price_eur": null,
    "stock": 45,
    "color": "Black",
    "material": "Organic cotton",
    "season": "All",
    "popularity": 63,
    "pairs_with": [
      "KE-M-001",
      "LU-M-004"
    ]
  },
  {
    "sku": "LU-U-003",
    "image": "LU-U-003.jpg",
    "image_lifestyle": "LU-U-003-2.jpg",
    "name_en": "Lounge jogger",
    "name_nl": "Lounge jogger",
    "brand": "Lün",
    "category": "Accessories",
    "subcategory": "Loungewear",
    "gender": "u",
    "price_eur": 29.95,
    "sale_price_eur": null,
    "stock": 17,
    "color": "Grey",
    "material": "Cotton blend",
    "season": "All",
    "popularity": 67,
    "pairs_with": [
      "LU-W-001",
      "LU-M-002"
    ]
  },
  {
    "sku": "LU-M-004",
    "image": "LU-M-004.jpg",
    "image_lifestyle": "LU-M-004-2.jpg",
    "name_en": "Crew sweatshirt",
    "name_nl": "Crew sweater",
    "brand": "Lün",
    "category": "Men",
    "subcategory": "Tops",
    "gender": "m",
    "price_eur": 27.95,
    "sale_price_eur": 19.95,
    "stock": 9,
    "color": "Sage",
    "material": "Cotton blend",
    "season": "All",
    "popularity": 65,
    "pairs_with": [
      "LU-M-002",
      "KE-M-001"
    ]
  },
  {
    "sku": "LU-W-005",
    "image": "LU-W-005.jpg",
    "image_lifestyle": "LU-W-005-2.jpg",
    "name_en": "Rib tank top",
    "name_nl": "Geribde tanktop",
    "brand": "Lün",
    "category": "Women",
    "subcategory": "Tops",
    "gender": "f",
    "price_eur": 9.95,
    "sale_price_eur": null,
    "stock": 60,
    "color": "White",
    "material": "Cotton",
    "season": "SS",
    "popularity": 52,
    "pairs_with": [
      "LU-W-001",
      "NO-W-007"
    ]
  },
  {
    "sku": "LU-U-006",
    "image": "LU-U-006.jpg",
    "image_lifestyle": "LU-U-006-2.jpg",
    "name_en": "Bucket hat",
    "name_nl": "Vissershoedje",
    "brand": "Lün",
    "category": "Accessories",
    "subcategory": "Hats",
    "gender": "u",
    "price_eur": 16.95,
    "sale_price_eur": null,
    "stock": 0,
    "color": "Black",
    "material": "Cotton",
    "season": "SS",
    "popularity": 48,
    "pairs_with": [
      "LU-U-003",
      "VO-A-004"
    ]
  },
  {
    "sku": "LU-W-007",
    "image": "LU-W-007.jpg",
    "image_lifestyle": "LU-W-007-2.jpg",
    "name_en": "Wide lounge pant",
    "name_nl": "Wijde lounge broek",
    "brand": "Lün",
    "category": "Women",
    "subcategory": "Loungewear",
    "gender": "f",
    "price_eur": 24.95,
    "sale_price_eur": null,
    "stock": 19,
    "color": "Taupe",
    "material": "Cotton blend",
    "season": "All",
    "popularity": 56,
    "pairs_with": [
      "LU-W-001",
      "LU-W-005"
    ]
  },
  {
    "sku": "LU-M-008",
    "image": "LU-M-008.jpg",
    "image_lifestyle": "LU-M-008-2.jpg",
    "name_en": "Zip hoodie",
    "name_nl": "Zip hoodie",
    "brand": "Lün",
    "category": "Men",
    "subcategory": "Tops",
    "gender": "m",
    "price_eur": 32.95,
    "sale_price_eur": null,
    "stock": 4,
    "color": "Navy",
    "material": "Cotton blend",
    "season": "All",
    "popularity": 62,
    "pairs_with": [
      "LU-M-002",
      "KE-M-001"
    ]
  },
  {
    "sku": "VO-A-001",
    "image": "VO-A-001.jpg",
    "image_lifestyle": "VO-A-001-2.jpg",
    "name_en": "Leather-look tote",
    "name_nl": "Leren-look shopper",
    "brand": "Vossen",
    "category": "Accessories",
    "subcategory": "Bags",
    "gender": "u",
    "price_eur": 39.95,
    "sale_price_eur": null,
    "stock": 12,
    "color": "Black",
    "material": "PU leather",
    "season": "All",
    "popularity": 81,
    "pairs_with": [
      "AO-W-005",
      "NO-W-002"
    ]
  },
  {
    "sku": "VO-A-002",
    "image": "VO-A-002.jpg",
    "image_lifestyle": "VO-A-002-2.jpg",
    "name_en": "Crossbody bag",
    "name_nl": "Crossbody tas",
    "brand": "Vossen",
    "category": "Accessories",
    "subcategory": "Bags",
    "gender": "u",
    "price_eur": 29.95,
    "sale_price_eur": 19.95,
    "stock": 7,
    "color": "Tan",
    "material": "PU leather",
    "season": "All",
    "popularity": 74,
    "pairs_with": [
      "KE-M-004",
      "AO-M-008"
    ]
  },
  {
    "sku": "VO-A-003",
    "image": "VO-A-003.jpg",
    "image_lifestyle": "VO-A-003-2.jpg",
    "name_en": "Woven belt",
    "name_nl": "Geweven riem",
    "brand": "Vossen",
    "category": "Accessories",
    "subcategory": "Belts",
    "gender": "u",
    "price_eur": 14.95,
    "sale_price_eur": null,
    "stock": 30,
    "color": "Brown",
    "material": "Leather",
    "season": "All",
    "popularity": 49,
    "pairs_with": [
      "AO-W-002",
      "KE-M-001"
    ]
  },
  {
    "sku": "VO-A-004",
    "image": "VO-A-004.jpg",
    "image_lifestyle": "VO-A-004-2.jpg",
    "name_en": "Knit beanie",
    "name_nl": "Gebreide muts",
    "brand": "Vossen",
    "category": "Accessories",
    "subcategory": "Hats",
    "gender": "u",
    "price_eur": 12.95,
    "sale_price_eur": null,
    "stock": 2,
    "color": "Mustard",
    "material": "Acrylic",
    "season": "AW",
    "popularity": 53,
    "pairs_with": [
      "KE-M-003",
      "LU-M-008"
    ]
  },
  {
    "sku": "VO-A-005",
    "image": "VO-A-005.jpg",
    "image_lifestyle": "VO-A-005-2.jpg",
    "name_en": "Canvas backpack",
    "name_nl": "Canvas rugzak",
    "brand": "Vossen",
    "category": "Accessories",
    "subcategory": "Bags",
    "gender": "u",
    "price_eur": 44.95,
    "sale_price_eur": 34.95,
    "stock": 6,
    "color": "Olive",
    "material": "Canvas",
    "season": "All",
    "popularity": 70,
    "pairs_with": [
      "KE-M-005",
      "LU-U-003"
    ]
  },
  {
    "sku": "VO-A-006",
    "image": "VO-A-006.jpg",
    "image_lifestyle": "VO-A-006-2.jpg",
    "name_en": "Sunglasses",
    "name_nl": "Zonnebril",
    "brand": "Vossen",
    "category": "Accessories",
    "subcategory": "Eyewear",
    "gender": "u",
    "price_eur": 19.95,
    "sale_price_eur": null,
    "stock": 0,
    "color": "Tortoise",
    "material": "Acetate",
    "season": "SS",
    "popularity": 58,
    "pairs_with": [
      "NO-W-002",
      "VO-A-001"
    ]
  },
  {
    "sku": "VO-A-007",
    "image": "VO-A-007.jpg",
    "image_lifestyle": "VO-A-007-2.jpg",
    "name_en": "Card holder",
    "name_nl": "Pasjeshouder",
    "brand": "Vossen",
    "category": "Accessories",
    "subcategory": "Small leather",
    "gender": "u",
    "price_eur": 11.95,
    "sale_price_eur": null,
    "stock": 24,
    "color": "Black",
    "material": "PU leather",
    "season": "All",
    "popularity": 44,
    "pairs_with": [
      "VO-A-001",
      "VO-A-002"
    ]
  },
  {
    "sku": "VO-A-008",
    "image": "VO-A-008.jpg",
    "image_lifestyle": "VO-A-008-2.jpg",
    "name_en": "Chunky scarf",
    "name_nl": "Dikke sjaal",
    "brand": "Vossen",
    "category": "Accessories",
    "subcategory": "Scarves",
    "gender": "u",
    "price_eur": 18.95,
    "sale_price_eur": null,
    "stock": 15,
    "color": "Burgundy",
    "material": "Acrylic",
    "season": "AW",
    "popularity": 51,
    "pairs_with": [
      "AO-W-005",
      "VO-A-004"
    ]
  }
];
